### ISSUE TITLE
Multiple Client and Server

### ISSUE THREAD

**Issue by ReiiYuki** [0angelic0/dgt-net#2]
Using dgt-net normally, it automatically create a client and a server. So it's seem as a problem if I want to do multi-server / multi-client architecture. It might be better if dgt-net is available to create multiple client / server.

**Comment by 0angelic0** [comment]
Nice suggestion! I will implement them soon.

**Comment by 0angelic0** [comment]
done! in dgt-net@1.1.0

Now you can use server.createServer() to create another server instance. And also client.createClient() to create another client instance.

**Comment by ReiiYuki** [comment]
Thank 👍 😃
